#version: '3.8'

services:
  load-balancer:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"
    depends_on:
      - api-1
      - api-2

  api-1:
    build:
      context: ./app
    hostname: api-1
    networks:
      - backend
      - payment-processor
    environment:
      - APP_PORT=8080
      - DB_PATH=/data/payments.db
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - PEER_URL=http://api-2:8080
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "165MB"
    volumes:
      - ./data/api-1:/data

  api-2:
    build:
      context: ./app
    hostname: api-2
    networks:
      - backend
      - payment-processor
    environment:
      - APP_PORT=8080
      - DB_PATH=/data/payments.db
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - PEER_URL=http://api-1:8080
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "165MB"
    volumes:
      - ./data/api-2:/data

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true